#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from turtlesim.msg import Pose
from turtlesim.srv import SetPen
from math import cos, sin, atan2, pi, atan, sqrt

dt = 0.1


class Tracker(Node):
    def __init__(self):
        super().__init__('tracker', namespace = 'turtle2')
        
        target = self.declare_parameter("target", 'turtle1').value
        
        # no pen
        pen_srv = self.create_client(SetPen, 'set_pen')
        pen_srv.wait_for_service()
        no_pen = SetPen.Request(off = 1)
        res = pen_srv.call_async(no_pen)
        rclpy.spin_until_future_complete(self, res)
        
        # subscribers
        self.pose = None
        self.pose_sub = self.create_subscription(Pose, 'pose', self.get_pose, 10)
        
        self.target = None
        self.target_sub = self.create_subscription(Pose, f'/{target}/pose', self.get_target_pose, 10)
        
        self.cmd = Twist()
        self.cmd_vel = self.create_publisher(Twist, 'cmd_vel', 10)
        
        self.timer = self.create_timer(dt, self.compute_cmd)
        
    def get_pose(self, msg):
        self.pose = msg
        
    def get_target_pose(self, msg):
        self.target = msg
        
    def move(self, vx, vy, w):
        
        self.cmd.linear.x = float(vx)
        self.cmd.linear.y = float(vy)
        self.cmd.angular.z = float(w)
        
        self.cmd_vel.publish(self.cmd)
        
    def compute_cmd(self):
        
        if self.pose is None or self.target is None:
            return

        # TODO follow the target


rclpy.init()
tracker = Tracker()

rclpy.spin(tracker)

# clean exit on Ctrl-C
tracker.destroy_node()
rclpy.shutdown()
